# Dependencies
markdown:         kramdown
highlighter:      rouge

gems:
  - jekyll-sitemap

# Permalinks
permalink:        pretty

# Setup
title:            Human Variome Project Australian Node
description:      Helping Australian diagnostic laboratories deliver better results for patients through secure data sharing.
url:              http://www.hvpaustralia.org.au
baseurl:          /

author:
  name:           'Human Variome Project Australian Node'
  url:            https://www.hvpaustralia.org.au
